version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bon-voyage-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bon_voyage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bon-voyage-network

  # Main Application
  app:
    build: .
    container_name: bon-voyage-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/bon_voyage
      - DIRECT_URL=postgresql://postgres:password123@postgres:5432/bon_voyage
      - PORT=3000
    depends_on:
      - postgres
    networks:
      - bon-voyage-network

volumes:
  postgres_data:

networks:
  bon-voyage-network:
    driver: bridge
